language: ruby
rvm:
- 2.3.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: Gmp3ShePGf3f05ghZ+7zOj+eVtxamdxcBySqvdKeaSG1IdqsvMguLC42iUrhJ6752Hfg9rlGC/FbFGr2boqe9XRgyhlVxVYBmJbIgSkJLy9uxvtEJGkKKxmJaOTTXi01z0idoMxcIpOFLW/CFY0RQRPn3aVpTpRr3o6Nx6Y9iW2qEPXcCZeJSJRFVg3tWal2+r0fwSdWywDrBePtkcN4h6lODVSftVTEX4+TZdESzAk5O1rB40sK02zr/mARapR5hoMUtI/ovAKC1awPsPZfWig6sk4LhUOS1EoLnbYKVaj2H0uCqbmS6F+gehrFuR+cJsrE6/p3RChCtf43Mzo/Fh7IcisCCSpyP18PMo+MnEfzb2D49JNMSdGHtRQ5a5hM4kXChyQUxqSuqI7/otdE0lmh+8emFLqaxi9R1fQQ5V8EpyYTx3Fyzu+aBgEnyRT37fyHy2OUW1QaYCTTC73mDnUpxsY+H6wFCsfI73VsXZnokwRktK4m/Rw1iy5J8UIE8LRFQKU4BAjlL/CpFwwbKjUyz3byfl1889GPFROm+YmLeGBW7RoJt5d9S0Zpg/Pq0lTdWUXuP4+/E9u+vzgIrYoBKEvrJ0kXO/ofQOae84ltF+OpLwhxSLNbrMcieD55iW7z2taxAMA140r1zNTvpp41i4MRP/EcI1Bg5Y5RskA=
  run: rake db:migrate
